import { ProfileEntity } from '@/domain/entities/Profile';

export const mockProfiles: ProfileEntity[] = [
  {
    id: '1',
    nom: 'Administrateur',
    description: 'Acces complet a toutes les fonctionnalites du systeme',
    role: 'Admin',
    permissions: [
      { resource: 'dashboard', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'plan', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'imports', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'forecast', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'users', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'profiles', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'settings', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'saisie', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'visualization', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'reporting', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'validation', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'position', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'rapprochement', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'notifications', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'echeancier', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'budget', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'historique', actions: ['view', 'create', 'edit', 'delete', 'export'] },
    ],
    isDefault: false,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    nom: 'Analyste Trésorerie',
    description: 'Gestion du plan de trésorerie, previsions et imports de donnees',
    role: 'Analyst',
    permissions: [
      { resource: 'dashboard', actions: ['view'] },
      { resource: 'plan', actions: ['view', 'create', 'edit'] },
      { resource: 'imports', actions: ['view', 'create'] },
      { resource: 'forecast', actions: ['view', 'create', 'edit'] },
      { resource: 'saisie', actions: ['view', 'create'] },
      { resource: 'visualization', actions: ['view'] },
      { resource: 'settings', actions: ['view'] },
      { resource: 'position', actions: ['view'] },
      { resource: 'rapprochement', actions: ['view', 'create'] },
      { resource: 'notifications', actions: ['view'] },
      { resource: 'echeancier', actions: ['view', 'create', 'edit'] },
      { resource: 'budget', actions: ['view'] },
      { resource: 'historique', actions: ['view'] },
    ],
    isDefault: true,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
  {
    id: '3',
    nom: 'Direction',
    description: 'Consultation et export des rapports et tableaux de bord',
    role: 'Direction',
    permissions: [
      { resource: 'dashboard', actions: ['view'] },
      { resource: 'plan', actions: ['view'] },
      { resource: 'forecast', actions: ['view'] },
      { resource: 'visualization', actions: ['view'] },
      { resource: 'reporting', actions: ['view', 'export'] },
      { resource: 'position', actions: ['view'] },
      { resource: 'validation', actions: ['view', 'edit'] },
      { resource: 'notifications', actions: ['view'] },
      { resource: 'echeancier', actions: ['view'] },
      { resource: 'budget', actions: ['view', 'export'] },
      { resource: 'historique', actions: ['view', 'export'] },
    ],
    isDefault: false,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
  {
    id: '4',
    nom: 'Controleur',
    description: 'Validation et controle des donnees de trésorerie',
    role: 'Controller',
    permissions: [
      { resource: 'dashboard', actions: ['view'] },
      { resource: 'plan', actions: ['view', 'edit'] },
      { resource: 'imports', actions: ['view'] },
      { resource: 'forecast', actions: ['view'] },
      { resource: 'visualization', actions: ['view'] },
      { resource: 'reporting', actions: ['view', 'export'] },
      { resource: 'validation', actions: ['view', 'create', 'edit'] },
      { resource: 'position', actions: ['view'] },
      { resource: 'rapprochement', actions: ['view', 'create', 'edit'] },
      { resource: 'notifications', actions: ['view'] },
      { resource: 'echeancier', actions: ['view', 'edit'] },
      { resource: 'budget', actions: ['view', 'export'] },
      { resource: 'historique', actions: ['view', 'export'] },
    ],
    isDefault: false,
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
];
